-m CtsMediaAudioTestCases
-m CtsMediaCodecTestCases
-m CtsMediaEncoderTestCases
-m CtsMediaV2TestCases
-m CtsCarTestCases
-m CtsUffdGcTestCases -t android.os.cts.uffdgc.UserfaultfdTest#nonUserModeOnlyUserfaultfd
-m CtsUffdGcTestCases -t android.os.cts.uffdgc.UserfaultfdTest#kernelSpaceUserfault
-m CtsUffdGcTestCases -t android.os.cts.uffdgc.UserfaultfdTest#selinuxEnabled
-m CtsUffdGcTestCases -t android.os.cts.uffdgc.UserfaultfdTest#mremapDontUnmap
-m CtsUffdGcTestCases -t android.os.cts.uffdgc.UserfaultfdTest#minorUserfaultfd
-m CtsNativeMediaAAudioTestCases